### ISSUE TITLE
Real 3D?

### ISSUE THREAD

**Issue by hurzl** [orbisgis/poly2tri.java#4]
Is this working for polygons in 3D, also for 3d polygons with a plane perpendicular to the xy plane?

**Comment by nicolas-f** [comment]
Poly2tri does not create additional points then it supports all attributes attached to x,y coordinates. Before tessellate a polygon you have to rotate it on the polygon plane, do the tessellation, then use the coordinate index (unchanged) for the final mesh.

**Comment by hurzl** [comment]
Ok thanks, from your example in the readme it could be expected that poly2tri would do all this by itself.

**Comment by hurzl** [comment]
... and how would I get the coordinate index?
